name: Bug report
description: Create a report to help us improve.
title: "[BUG] - "
body:
  - type: markdown
    attributes:
      value: |
        A clear and concise description of what the bug is.

  - type: textarea
    attributes:
      label: Description
      description: A detailed description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Affected JSDelivr link
      description: One or more direct links that are affected by this issue.
      placeholder: |
       cdn.jsdeivr.net/example/example1.js
       cdn.jsdeivr.net/example/example2.json
       ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Response headers
      description: A complete list of response headers for one affected link, copied from browser developer tools or curl.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce (add screenshots if applicable)
      placeholder: |
        1. [First step] (Screenshot 1)
        2. [Second step] (Screenshot 2)
        3. [And so on...] (Screenshot X)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Information
      description: The following information is needed for us to define the problem.
      placeholder: |
        - Device OS: [e.g. IOS, Windows, MacOS]
        - Browser & Version: [e.g. Chrome 103, safari 8, Firefox 108]
        - VPN provider (if you use one)
        - Your location (country/region)
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Requisites
      description: |
        To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: I performed a [cursory search of the issue tracker](https://github.com/jsdelivr/jsdelivr/issues?q=is%3Aissue) to avoid opening a duplicate issue.
          required: true
        - label: I checked the [documentation](https://github.com/jsdelivr/jsdelivr/wiki) to understand that the issue I am reporting is not normal behavior.
          required: true
        - label: I understand that not filling out this template correctly will lead to the issue being closed.
          required: true

  - type: textarea
    attributes:
      label: Additional content
      description: Anything you want to add.
    validations:
